import Hero from "./Hero";
import Services from "./Services";
import Aboutus from "./Aboutus";
import Consulting from "./Consulting";
import Catering from "./Catering";
import Menu from "./Menu";
import Testimonials from "./Testimonials";
import CTA from "./CTA";
import Footer from "./Footer";